# RDS, chapter 9
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("rds07.tst");

# doc/../lib/misc.gd:48-55
gap> G:=Group((1,2,3),(2,3));
Group([ (1,2,3), (2,3) ])
gap> alpha:=InnerAutomorphism(G,(1,2,3));
^(1,2,3)
gap> OnSubgroups(Subgroup(G,[(2,3)]),alpha);
Group([ (1,3) ])

# doc/../lib/misc.gd:173-176
gap> RepsCClassesGivenOrder(SymmetricGroup(5),2);
[ (4,5), (2,3)(4,5) ]

# doc/../lib/reps.gd:130-133
gap> List2Tuples([1..6],2);
[ [ 1 .. 3 ], [ 4 .. 6 ] ]

# doc/../lib/reps.gd:161-168
gap> CycsGivenCoeffSum(3,E(3));
[ [ 0, [ [ 1, 1, 1 ] ] ], 
  [ 3, [ [ 0, 1, 2 ], [ 0, 2, 1 ], [ 1, 0, 2 ], [ 1, 2, 0 ], [ 2, 0, 1 ], 
          [ 2, 1, 0 ] ] ], [ 9, [ [ 0, 0, 3 ], [ 0, 3, 0 ], [ 3, 0, 0 ] ] ] ]
gap> CycsGivenCoeffSum(2,E(2));
[ [ 0, [ [ 1, 1 ] ] ], [ 4, [ [ 0, 2 ], [ 2, 0 ] ] ] ]

# doc/misc.xml:146-163
gap> IsComputableFilter( IsFinite );
true
gap> IsComputableFilter( HasSize );
true
gap> IsComputableFilter( HasIsFinite );
true
gap> IsComputableFilter( IsPositionalObjectRep );
false
gap> IsComputableFilter( IsInt );
false
gap> IsComputableFilter( IsQuickPositionList );
false
gap> IsComputableFilter( IsInt and IsPosRat );
false
gap> IsComputableFilter( IsMagma );
false

#
gap> STOP_TEST("rds07.tst", 1);
